# Results
```{r}
data_15_20_household <- read.csv("data_train/data_15_20_household.csv")
data_15_20_race <- read.csv("data_train/data_15_20_race.csv")
data_15_20_region <- read.csv("data_train/data_15_20_region.csv")
data_19_20_edu <- read.csv("data_train/data_19_20_edu.csv")
data_20_age <- read.csv("data_train/data_20_age.csv")
fm_ern_new <- read.csv("data_train/fm_ern_new.csv")
house_67_20_new <- read.csv("data_train/house_67_20_new.csv")
library(dplyr)
library(tidyverse)
library(tidyr)
library(tibble)
library(ggplot2)
a <- house_67_20_new %>% 
  filter(.,Year == 2020) %>%
  select(c(4:12,17))

b <- as.data.frame(t(a))

colnames(b)<-b[10,]
b <- b[-10,]
b$income_perc <- c("under 15", "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200")
b$income_perc=as.factor(b$income_perc)

# 2*4

  race_col <- b[,1]
bar1<- ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col))+
  geom_bar(stat="identity", fill = "steelblue", alpha = 0.5) + 
  xlab("income_range")+
    ylab("ALL RACES")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by ALL RACES")
  

    race_col2 <- b[,2]
bar2<-  ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col2))+
  geom_bar(stat="identity", fill = "thistle", alpha = 0.5) + 
  xlab("income_range")+
    ylab("WHITE ALONE 24")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col2, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by WHITE ALONE 24")
  
      race_col3 <- b[,3]
  bar3<-ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col3))+
  geom_bar(stat="identity", fill = "tomato", alpha = 0.5) + 
  xlab("income_range")+
    ylab("WHITE ALONE, NOT HISPANIC 24")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col3, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by WHITE ALONE, NOT HISPANIC 24")
  
      race_col4 <- b[,4]
bar4<-  ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col4))+
  geom_bar(stat="identity", fill = "turquoise", alpha = 0.5) + 
  xlab("income_range")+
    ylab("BLACK ALONE OR IN COMBINATION")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col4, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by BLACK ALONE OR IN COMBINATION")
  

  
      race_col5 <- b[,5]
bar5<-  ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col5))+
  geom_bar(stat="identity", fill = "violet", alpha = 0.5) + 
  xlab("income_range")+
    ylab("BLACK ALONE 26")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col5, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by BLACK ALONE 26")
  
      race_col6 <- b[,6]
bar6<-  ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col6))+
  geom_bar(stat="identity", fill = "wheat", alpha = 0.5) + 
  xlab("income_range")+
    ylab("ASIAN ALONE OR IN COMBINATION")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col6, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by ASIAN ALONE OR IN COMBINATION")
  
      race_col7 <- b[,7]
 bar8<- ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col7))+
  geom_bar(stat="identity", fill = "yellow", alpha = 0.5) + 
  xlab("income_range")+
    ylab("ASIAN ALONE 27")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col7, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by ASIAN ALONE 27")
  
      race_col8 <- b[,8]
bar9<-  ggplot(b,aes(fct_relevel(income_perc,"under 15",
                         "15-25","25-35","35-50","50-75","75-100","100-150","150-200","above 200"),race_col8))+
  geom_bar(stat="identity", fill = "pink", alpha = 0.5) + 
  xlab("income_range")+
    ylab("HISPANIC (ANY RACE) 28")+
  coord_flip()+
    geom_text(aes(label = paste0(race_col8, "%")), color = "gray20", hjust =-0.2,size=3.2)+ggtitle("Plot of income range by HISPANIC (ANY RACE) 28")
library(ggpubr) 
ggarrange(bar1,bar2,bar3,bar4,bar5,bar6,bar7,bar8,nrow=4,ncol=3) 
  
  

  
```


```{r}

#stacked bar chart for education


ggplot(data_19_20_edu, aes(fill=Education, y=median_income, x=Year)) + 
    geom_bar(position="stack", stat="identity")+ggtitle("Stacked Barchart for income by education 19-20")+coord_flip()+ scale_x_continuous(breaks = seq(2019, 2020, by = 1))+scale_y_continuous(labels = scales::dollar_format())
```

```{r}
library(ggplot2)
data_20_household <-data_15_20_household[which(data_15_20_household$Year==2020),]
hhbar1<-ggplot(data_20_household,aes(x=Type.of.Households,y=median_income))+  geom_bar(stat="identity", fill = "aquamarine", alpha = 0.7)+ scale_x_discrete(guide = guide_axis(angle = 90))+ggtitle("type of household by median_income in 2020")+
  scale_y_continuous(labels = scales::dollar_format()) 

data_20_region <- data_15_20_region[which(data_15_20_region$Year==2020),]
regionbar2<-ggplot(data_20_region,aes(x=Region,y=median_income))+  geom_bar(stat="identity", fill = "cadetblue", alpha = 0.7) +ggtitle("Region by median_income in 2020")

ggarrange(hhbar1,regionbar2,ncol=1,nrow=2, vjust = 1.5)
```

```{r}
fm_ern %>% filter(Year>2014)
```

